/** Parsed `shapebot.properties` (subset). Mirrors [BoardMachine.read_machine_data](boardcad-java/boardcam/BoardMachine.java). */
export type ShapebotConfig = {
  deckScript: string;
  bottomScript: string;
  deckCuts: number;
  bottomCuts: number;
  speed: number;
  toolName: string;
  zMaxHeight: number;
};

export function parseShapebotProperties(text: string): ShapebotConfig {
  const lines = text.split(/\r?\n/);
  const map = new Map<string, string>();
  for (const line of lines) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq < 0) continue;
    map.set(t.slice(0, eq).trim(), t.slice(eq + 1).trim());
  }
  return {
    deckScript: map.get("toolpathGenerator.deckScript") ?? "shapebot5deck.py",
    bottomScript: map.get("toolpathGenerator.bottomScript") ?? "shapebot5bottom.py",
    deckCuts: Number(map.get("g.deckCuts") ?? 20),
    bottomCuts: Number(map.get("g.bottomCuts") ?? 20),
    speed: Number(map.get("g.speed") ?? 10000),
    toolName: map.get("g.toolName") ?? "flatcutter.stl",
    zMaxHeight: Number(map.get("g.zMaxHeight") ?? 500),
  };
}

/** Minimal G-code header writer (parity path toward GCodeWriter.java). */
export function writeGcodeHeaderComment(machineLabel = "RippleStudio-CAM"): string {
  return `; Generated by ${machineLabel}\n; Units: mm\n`;
}

/** TS port stub: deck toolpath (full parity = shapebot*.py + STLCutter). */
export function generateGcodeDeckStub(_cfg: ShapebotConfig): string {
  return `${writeGcodeHeaderComment()}G21\nG90\n; deck toolpath stub\n`;
}

export function generateGcodeBottomStub(_cfg: ShapebotConfig): string {
  return `${writeGcodeHeaderComment()}G21\nG90\n; bottom toolpath stub\n`;
}
